### ISSUE TITLE
Error i Redmine 4.1.3

### ISSUE THREAD

**Issue by koren85** [AlphaNodes/sidebar_hide#1]
Hi,
I am getting an error in my development environment Redmine 4.1.3:

```
ActionView::Template::Error (Missing partial sidebar/_hide_button with {:locale=>[:ru, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/westaco_versions/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/sidebar_hide/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/redmine_entity_generator/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/redmine_custom_workflows/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/redmine_custom_values_projects/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/redmine_contract_job/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/redmine_checklists/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/redmine_banner/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/custom_field_sql/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/accept/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/plugins/a_common_libs/app/views"
  * "C:/Users/admin/Documents/redmine-4.1.3/redmine-4.1.3/app/views"
  * "C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/redmine_extensions-0.4.1/app/views"
  * "C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/redmine_crm-0.0.54/app/views"
):
    109:         <%= view_layouts_base_sidebar_hook_response %>
    110:     </div>
    111:
    112:     <div id="content">
    113:         <%= render_flash_messages %>
    114:         <%= yield %>
    115:         <%= call_hook :view_layouts_base_content %>

lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:59:in `map'
lib/redmine/hook/view_listener.rb:59:in `block in render_on'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:98:in `call_hook'
app/views/layouts/base.html.erb:112:in `_df4580eb642fd600db5a487fbbd4e545'
app/controllers/application_controller.rb:526:in `block (2 levels) in render_error'
app/controllers/application_controller.rb:524:in `render_error'
app/controllers/application_controller.rb:512:in `render_404'
app/controllers/application_controller.rb:536:in `missing_template'
```

**Comment by alexandermeindl** [comment]
Hi @koren85 

thanks for reporting this. I fixed it with my last commit. Please use installation instruction on https://github.com/AlphaNodes/sidebar_hide

Let me know, if it works for you.

**Comment by koren85** [comment]
Great, works for me! Thank you!
